name: Deploy to Fly.io
on:
  push:
    branches:
    - main
jobs:
  fly:
    runs-on: ubuntu-latest
    environment:
      name: prod
      url: "https://pbot-crawler.fly.dev/"
    steps:
    - uses: actions/checkout@v7
    - uses: superfly/flyctl-actions/setup-flyctl@master
    - name: Deploy the updated app.
      run: flyctl deploy fly
      env:
        FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        NO_COLOR: 1
